/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: measure.proto */

#ifndef PROTOBUF_C_measure_2eproto__INCLUDED
#define PROTOBUF_C_measure_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Measure__MeasureMsg Measure__MeasureMsg;


/* --- enums --- */


/* --- messages --- */

struct  Measure__MeasureMsg
{
  ProtobufCMessage base;
  uint32_t size;
  char *timestamp;
  int32_t temperature;
  uint32_t humidity;
};
#define MEASURE__MEASURE_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&measure__measure_msg__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0 }


/* Measure__MeasureMsg methods */
void   measure__measure_msg__init
                     (Measure__MeasureMsg         *message);
size_t measure__measure_msg__get_packed_size
                     (const Measure__MeasureMsg   *message);
size_t measure__measure_msg__pack
                     (const Measure__MeasureMsg   *message,
                      uint8_t             *out);
size_t measure__measure_msg__pack_to_buffer
                     (const Measure__MeasureMsg   *message,
                      ProtobufCBuffer     *buffer);
Measure__MeasureMsg *
       measure__measure_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   measure__measure_msg__free_unpacked
                     (Measure__MeasureMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Measure__MeasureMsg_Closure)
                 (const Measure__MeasureMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor measure__measure_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_measure_2eproto__INCLUDED */
