/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: measure.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "measure.pb-c.h"
void   measure__measure_msg__init
                     (Measure__MeasureMsg         *message)
{
  static const Measure__MeasureMsg init_value = MEASURE__MEASURE_MSG__INIT;
  *message = init_value;
}
size_t measure__measure_msg__get_packed_size
                     (const Measure__MeasureMsg *message)
{
  assert(message->base.descriptor == &measure__measure_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t measure__measure_msg__pack
                     (const Measure__MeasureMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &measure__measure_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t measure__measure_msg__pack_to_buffer
                     (const Measure__MeasureMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &measure__measure_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Measure__MeasureMsg *
       measure__measure_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Measure__MeasureMsg *)
     protobuf_c_message_unpack (&measure__measure_msg__descriptor,
                                allocator, len, data);
}
void   measure__measure_msg__free_unpacked
                     (Measure__MeasureMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &measure__measure_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor measure__measure_msg__field_descriptors[4] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Measure__MeasureMsg, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Measure__MeasureMsg, timestamp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Measure__MeasureMsg, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Measure__MeasureMsg, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned measure__measure_msg__field_indices_by_name[] = {
  3,   /* field[3] = humidity */
  0,   /* field[0] = size */
  2,   /* field[2] = temperature */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange measure__measure_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor measure__measure_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "measure.MeasureMsg",
  "MeasureMsg",
  "Measure__MeasureMsg",
  "measure",
  sizeof(Measure__MeasureMsg),
  4,
  measure__measure_msg__field_descriptors,
  measure__measure_msg__field_indices_by_name,
  1,  measure__measure_msg__number_ranges,
  (ProtobufCMessageInit) measure__measure_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
