/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testmsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "testmsg.pb-c.h"
void   testmsg__testmsg__init
                     (Testmsg__Testmsg         *message)
{
  static const Testmsg__Testmsg init_value = TESTMSG__TESTMSG__INIT;
  *message = init_value;
}
size_t testmsg__testmsg__get_packed_size
                     (const Testmsg__Testmsg *message)
{
  assert(message->base.descriptor == &testmsg__testmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testmsg__testmsg__pack
                     (const Testmsg__Testmsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testmsg__testmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testmsg__testmsg__pack_to_buffer
                     (const Testmsg__Testmsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testmsg__testmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testmsg__Testmsg *
       testmsg__testmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testmsg__Testmsg *)
     protobuf_c_message_unpack (&testmsg__testmsg__descriptor,
                                allocator, len, data);
}
void   testmsg__testmsg__free_unpacked
                     (Testmsg__Testmsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testmsg__testmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor testmsg__testmsg__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testmsg__Testmsg, timestamp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Testmsg__Testmsg, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Testmsg__Testmsg, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testmsg__testmsg__field_indices_by_name[] = {
  2,   /* field[2] = humidity */
  1,   /* field[1] = temperature */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange testmsg__testmsg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor testmsg__testmsg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testmsg.Testmsg",
  "Testmsg",
  "Testmsg__Testmsg",
  "testmsg",
  sizeof(Testmsg__Testmsg),
  3,
  testmsg__testmsg__field_descriptors,
  testmsg__testmsg__field_indices_by_name,
  1,  testmsg__testmsg__number_ranges,
  (ProtobufCMessageInit) testmsg__testmsg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
