/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testmsg.proto */

#ifndef PROTOBUF_C_testmsg_2eproto__INCLUDED
#define PROTOBUF_C_testmsg_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Testmsg__Testmsg Testmsg__Testmsg;


/* --- enums --- */


/* --- messages --- */

struct  Testmsg__Testmsg
{
  ProtobufCMessage base;
  char *timestamp;
  int32_t temperature;
  uint32_t humidity;
};
#define TESTMSG__TESTMSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testmsg__testmsg__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


/* Testmsg__Testmsg methods */
void   testmsg__testmsg__init
                     (Testmsg__Testmsg         *message);
size_t testmsg__testmsg__get_packed_size
                     (const Testmsg__Testmsg   *message);
size_t testmsg__testmsg__pack
                     (const Testmsg__Testmsg   *message,
                      uint8_t             *out);
size_t testmsg__testmsg__pack_to_buffer
                     (const Testmsg__Testmsg   *message,
                      ProtobufCBuffer     *buffer);
Testmsg__Testmsg *
       testmsg__testmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   testmsg__testmsg__free_unpacked
                     (Testmsg__Testmsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Testmsg__Testmsg_Closure)
                 (const Testmsg__Testmsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor testmsg__testmsg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_testmsg_2eproto__INCLUDED */
